# spring全家桶
spring:
  application:
    name: warriors-gateway-zuul  # 唯一的服务名称或者也可以称为ID
  security:
    basic:
      enabled: false    # 关闭弹出的默认认证登录框
    user:
      name: eureka      # 配置登录的账号是user
      password: eureka  # 配置登录的密码是password123
  # bus 消息总线
  bus:
    enabled: true       # 开启配置刷新
  #rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

# 网关的配置
zuul:
  prefix: /api    # 配置统一的前缀
  ignored-services: warriors-war-user
  routes:
    warriors-war-user:               # 需要唯一 建议配置为serviceId
      path: /mine/**                    # /映射的简单路径/**   两个*标识所有的映射
      serviceId: warriors-war-user   # serviceId 服务的Id

# monitor 监控配置
management:
  security:
    enabled: false  # 关闭框架刷新安全校验
  endpoints:
    web:
      exposure:
        include: "*"  # 监控端点全部暴露*在yaml 文件属于关键字，所以需要加引号
  endpoint:
    health:
      show-details: ALWAYS # 心跳端点全部暴露

# sql输出级别
logging:
  level:
    com:
      mine:
        warriorsgateway:
          mapper: debug