#spring全家桶
spring:
  application:
    name: warriors-server-aop  # 唯一的服务名称或者也可以称为ID
  security:
    basic:
      enabled: false    # 关闭弹出的默认认证登录框
    user:
      name: eureka      # 配置登录的账号是user
      password: eureka  # 配置登录的密码是password123
  # bus消息总线配置刷新
  bus:
    enabled: true
  #rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

#sql输出级别
logging:
  level:
    com:
      mine:
        warriorsserveraop:
          mapper: debug

management:
  security:
    enabled: false  # 关闭框架刷新安全校验
  endpoints:
    web:
      exposure:
        include: "*"  # 监控端点全部暴露*在yaml 文件属于关键字，所以需要加引号
  endpoint:
    health:
      show-details: ALWAYS # 心跳端点全部暴露