server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/

spring:
  application:
    name: warriors-config-center
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/mine-lee/warriors-party.git
          search-paths: warriors-config-repo/*
          username:
          password:



