server:
  port: 8888

spring:
  application:
    name: warriors-config-center
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/mine-lee/warriors-party.git   # git 路径
          search-paths: warriors-config-repo/*                  # 文件夹<可配置多个，用逗号分隔>
          username:
          password:

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 3     # 服务失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 1        # 服务续约的间隔，默认为30秒
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/

# http请求地址和资源文件映射如下:
#     /{application}/{profile}/{label}
#     /{application}-{profile}.yml
#     /{label}/{application}-{profile}.yml
#     /{application}-{profile}.properties
#     /{label}/{application}-{profile}.properties

