server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 2        # 服务续约周期，默认为30秒
    lease-expiration-duration-in-seconds: 3     # 服务失效时间，默认值90秒
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/

spring:
  application:
    name: warriors-config-center
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/mine-lee/warriors-party.git
          search-paths: warriors-config-repo/*
          username:
          password:



