server:
  port: 8763
#  session:
#    cookie:
#      name: warriors-gateway-zuul-session    # 网关的session名字，建议每个微服务都单独命名
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1        # 服务续约周期，默认为30秒
    lease-expiration-duration-in-seconds: 1     # 服务失效时间，默认值90秒
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: warriors-gateway-zuul
  security:
    basic:
      enabled : false   # #关闭弹出的默认认证登录框

zuul:
  prefix: /api    # 配置统一的前缀
#  add-host-header: true   # 网关在进行请求路由转发前为请求设置Host头信息。不会暴露真实地址
#  ignored-services: /warriors-server-aop/**        # 配置不需要映射的服务Id
#  ignored-patterns: /**/hello/**                   # 配置不需要映射的接口
  ignoreSecurityHeaders: false      # 是否忽略与权限相关的头信息(默认true)
  sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods   # 敏感头信息（不向下传递）
  retryable: false    # 关闭全局重试机制：
  connectTimeoutMillis: 10000  # 超时时间
# 如果需要对某个服务进行一个不同方式处理的话需要这些下面的配置 --- begin ---
#  routes:
#    warriors-server-aop:
#      path: /warriors-server-aop/**
#      serviceId: warriors-server-aop
#      sensitiveHeaders: sensitive   # 会过滤服务之间通信附带的headers(不向下传递)
#      retryable: false              # 关闭某一个服务的重试机制
# 如果需要对某个服务进行一个不同方式处理的话需要这些下面的配置 --- finish ---
#    warriors-server-mybatis-plus:
#      path: /warriors-server-mybatis-plus/**
#      serviceId: warriors-server-mybatis-plus

logging:
  config: classpath:./logback-spring.xml
  path: D:/workspace/my/_java/log/warriors-gateway-zuul
  file: D:/workspace/my/_java/log/warriors-gateway-zuul/console.log
