server:
  port: 8000

spring:
  application:
    name: ws-sms-gateway
  profiles:
    active: dev
  cloud:
    inetutils:
      default-ip-address: 127.0.0.1
    #gateway:
      #default-filters:
      #- PrefixPath=/wx
      #- AddResponseHeader=X-Response-Default-Foo, Default-Bar
    gateway:
      enabled: true #关闭/启动网关  true：打开网关； false；关闭网关
      discovery:
        locator:
          lowerCaseServiceId: true  #配置完成之后我们就可以通过小写的服务名称进行访问了; http://网关地址/服务名称（小写）/**
          # 是否可以通过其他服务的serviceId来转发到具体的服务实例。默认为false
          # 为true,自动创建路由,路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问
          enabled: true

      #routes:
        # 路由到其他服务,url需要用[lb://]+[serviceId]
        #- id: wx-sms-base
        #  uri: lb://WX_SMS_BASE  #这里的uri不是一个具体的地址了,而是lb://开头,加上serviceId   WX_SMS_BASE大写不行；
        #  predicates:
        #    - Path=/WX_SMS_BASE/**  #如果请求地址满足/v3/**,则转发到wx-sms-base 服务
        #  filters:
        #    - StripPrefix=1 # 去除请求地址中的to_client
        #- id: path_route
        #  uri: http://127.0.0.1:8003
        #  predicates:
        #    - Path=/wx-sms-base/** # 请求地址携带wx-sms-base的,则转发 http://127.0.0.1:8003/
        #  filters:
        #    - StripPrefix=1 # 去除请求地址中的to_client



eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.inetutils.default-ip-address}:${server.port}
  client:
    #registerWithEureka: true
    #fetchRegistry: true
    serviceUrl:
      defaultZone: http://wxeureka:wxeurekapw@127.0.0.1:8761/eureka/

