server:
  port: 9999

spring:
  application:
    name: warriors-gateway-center
  gateway:
    default-filters:
      - PrefixPath=/api
    enabled: true #关闭/启动网关  true：打开网关； false；关闭网关
    discovery:
      locator:
        lowerCaseServiceId: true  #配置完成之后我们就可以通过小写的服务名称进行访问了; http://网关地址/服务名称（小写）/**
        enabled: true
  security:
    user:
      name: eureka
      password: eureka

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8761/eureka/

