server:
  port: 9999

spring:
  application:
    name: warriors-gateway-center
  cloud:
    gateway:
      enabled: true
#      default-filters:
#        - PrefixPath=/mine
      discovery:
        locator:
          lowerCaseServiceId: true  #配置完成之后我们就可以通过小写的服务名称进行访问了; http://网关地址/服务名称（小写）/**
          # 是否可以通过其他服务的serviceId来转发到具体的服务实例。默认为false
          # 为true,自动创建路由,路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问
          enabled: true


  security:
    user:
      name: eureka
      password: eureka

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8761/eureka/

