server:
  port: 8000

spring:
  application:
    name: warriors-server-eureka
  security:
    user:
      name: eureka
      password: eureka

eureka:
  instance:           
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka:eureka@127.0.0.1:8000/eureka/