server:
  port: 8000

spring:
  application:
    name: warriors-eureka-center
  security:
    user:
      name: eureka
      password: eureka

eureka:
  instance:           
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 2        # 服务续约周期，默认为30秒
    lease-expiration-duration-in-seconds: 3     # 服务失效时间，默认值90秒
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka:eureka@127.0.0.1:8000/eureka/