server:
  port: 8761

spring:
  application:
    name: warriors-server-eureka
  security:
    basic:
      enabled: false
    user:
      name: eureka
      password: eureka

eureka:
  instance:
    prefer-ip-address: true               # 使用IP注册（默认关闭缺省值为机器名）
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    registerWithEureka: false             # 不要向注册中心注册自己
    fetchRegistry: false                  # 表示不去检索其他的服务
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8761/eureka



