management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: warriors-server-mybatis-plus
  security:
    basic:
      enabled: false
    user:
      name: eureka
      password: eureka
  rabbitmq:
    host: 176.122.189.97
    port: 5672
    username: admin
    password: admin
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
#    注释的部分是单数据源的配置方式
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/warriors
        slave_1:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test
        slave_2:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test1

#mybatis-plus
mybatis-plus:
  #实体扫描<包>，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mine.warriorsservermybatisplus.entity
  #mapper配置
  mapper-locations: classpath:/mapper/**Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面2个配置）
    logic-delete-value: 1         # 逻辑删除
    logic-not-delete-value: 0     # 存在
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    com:
      mine:
        warriorsservermybatisplus:
          mapper: debug
