server:
  port: 9999

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 2        # 服务续约周期，默认为30秒
    lease-expiration-duration-in-seconds: 3     # 服务失效时间，默认值90秒
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/

spring:
  application:
    name: warriors-gateway-zuul

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  prefix: /api
  routes:
    warriors-server-rabbitMQ:
      path: /warriors-server-rabbitMQ/**
      serviceId: warriors-server-rabbitMQ
    warriors-server-element:
      path: /warriors-server-element/**
      serviceId: warriors-server-element


