server:
  port: 8763

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 2        # 服务续约周期，默认为30秒
    lease-expiration-duration-in-seconds: 3     # 服务失效时间，默认值90秒
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@127.0.0.1:8761/eureka/

spring:
  application:
    name: warriors-gateway-zuul

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  add-host-header: true   # 网关在进行请求路由转发前为请求设置Host头信息。不会暴露真实地址
  prefix: /api    # 配置统一的前缀
#  ignored-services: /warriors-server-aop/**   # 配置不需要映射的服务Id
#  ignored-patterns: /**/hello/**                   # 配置不需要映射的接口
  routes:
    warriors-server-rabbitMQ:
      path: /warriors-server-aop/**
      serviceId: warriors-server-aop
      sensitiveHeaders: token   # 默认情况下，敏感的头信息无法经过API网关进行传递，我们可以通过如下配置使之可以传递
#    warriors-server-mybatis-plus:
#      path: /warriors-server-mybatis-plus/**
#      serviceId: warriors-server-mybatis-plus

logging:
  config: classpath:./logback-spring.xml
  path: D:/warriors-gateway-zuul/log
