server:
  port: 8102

spring:
  application:
    name: warriors-server-feign

# springcloud2.0 以后feign的容错机默认是关闭的。需要我们进行如下配置开启
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/


