spring:
  cloud:
    config:
      name: warriors-server-element
      discovery:
        enabled: true
        serviceId: warriors-config-center # 配置中心的ID
      label: master   # git 默认就是master
      profile: dev
    bus:
      enabled: true
      trace:
        enabled: true # 开启消息跟踪

management:
  security:
    enabled: false    # 刷新时关闭安全验证
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 3     # 服务失效时间，默认值90秒
    lease-renewal-interval-in-seconds: 1        # 服务续约的间隔，默认为30秒
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
