#服务端口
server:
  port: 8004

#基于Eureka的注册中心
eureka:
  instance:
    #    ip-address: 127.0.0.1                       # 指定IP地址，缺省读取本机IPv4地址（无论服务中心是在公网，还是在内网）
    prefer-ip-address: true                     # 使用IP注册（默认关闭缺省值为机器名）
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1        # 服务续约周期，缺省值为30s
    lease-expiration-duration-in-seconds: 1     # 服务失效时间，缺省值为90s
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@127.0.0.1:8000/eureka/

# spring全家桶
spring:
  application:
    name: warriors-server-redis
  # rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # redis
  cache:
    type: redis
  redis:
    database: 0
    password:
    timaout: 2000
    cluster:
      nodes:
        - 127.0.0.1:6379
        - 127.0.0.1:6380
        - 127.0.0.1:6381
        - 127.0.0.1:6379
        - 127.0.0.1:6380
        - 127.0.0.1:6381
    jedis:
      pool:
        max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8     # 连接池中的最大空闲连接
        min-idle: 2     # 连接池中的最小空闲连接
        max-wait: 100   # 连接池最大阻塞等待时间（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8     # 连接池中的最大空闲连接
        min-idle: 2     # 连接池中的最小空闲连接
        max-wait: 100   # 连接池最大阻塞等待时间（使用负值表示没有限制）
# log输出级别
logging:
  level:
    com:
      mine:
        warriorsserverredis:
          mapper: debug
