server:
  port: 8769

spring:
  application:
    name: warriors-monitor-admin
  security:
    user:
      name: eureka
      password: eureka

#基于Eureka的注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
    # matedata-map中的user.name 和 user.password 必须配置且必须与security一致 否则监控本身的心跳是 DOWN
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@176.122.189.97:8761/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

info:
  project:
    name: @project.artifactId@
    version: @project.version@
    description: @project.description@
  spring:
    boot.version: @spring-boot.version@
    cloud.version: @spring-cloud.version@
  author: mine-lee
  blog: https://mine-lee.github.io/warriors-party/

logging:
  config: classpath:logback-spring.xml
#  path: /usr/java/log/warriors-monitor-admin
#  file: /usr/java/log/warriors-monitor-admin/console.log
  path: D:/workspace/my/_java/log/warriors-monitor-admin
  file: D:/workspace/my/_java/log/warriors-monitor-admin/console.log