server:
  port: 8764

#spring全家桶
spring:
  application:
    name: warriors-monitor-admin  # 唯一的服务名称或者也可以称为ID
  security:
    user:
      name: admin
      password: admin

#基于Eureka的注册中心
eureka:
  instance:
    #    ip-address: 127.0.0.1                       # 指定IP地址，缺省读取本机IPv4地址
    prefer-ip-address: true                     # 使用IP注册（默认关闭缺省值为机器名）
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1        # 服务续约周期，缺省值为30s
    lease-expiration-duration-in-seconds: 1     # 服务失效时间，缺省值为90s
    # matedata-map中的user.name 和 user.password 必须配置且必须与security一致 否则监控本身的心跳是 DOWN
    metadata-map:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@127.0.0.1:8761/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

info:
  project:
    name: @project.artifactId@
    version: @project.version@
    description: @project.description@
  spring:
    boot.version: @spring-boot.version@
    cloud.version: @spring-cloud.version@
  author: mine-lee
  blog: https://mine-lee.github.io/warriors-party/

logging:
  config: classpath:./logback-spring.xml
  path: D:/workspace/my/_java/log/warriors-monitor-admin
  file: D:/workspace/my/_java/log/warriors-monitor-admin/console.log