spring:
  application:
    name: warriors-server-rabbitMQ
  rabbitmq:
    host: 176.122.189.97
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true

#sql输出级别
logging:
  level:
    com:
      mine:
        warriorsserverrabbitmq:
          mapper: debug
