#服务端口
server:
  port: 8006

#基于Eureka的注册中心
eureka:
  instance:
    #    ip-address: 127.0.0.1                       # 指定IP地址，缺省读取本机IPv4地址（无论服务中心是在公网，还是在内网）
    prefer-ip-address: true                     # 使用IP注册（默认关闭缺省值为机器名）
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1        # 服务续约周期，缺省值为30s
    lease-expiration-duration-in-seconds: 1     # 服务失效时间，缺省值为90s
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@176.122.189.97:8761/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS    # 现实数据源以及磁盘使用的详情等

#spring全家桶
spring:
  application:
    name: warriors-server-logback  # 唯一的服务名称或者也可以称为ID
  security:
    user:
      name: eureka      # 配置登录的账号是user
      password: eureka  # 配置登录的密码是password123
#  main:
#    banner-mode: "off"  # 关闭启动图案
#sql输出级别
logging:
  level:
    com:
      mine:
        warriorsserverlogback:
          mapper: debug
  config: classpath:logback-spring.xml
  file: /usr/java/log/warriors-server-logback.log
